environment:
  VisualStudioVersion: 11.0

shallow_clone: true

configuration:
#  - Debug
  - Release

platform:
  - x64
  -
  - Win32
  - x86

before_build:
  - cmd: nuget restore

# MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed

build:
#  verbosity: detailed
  verbosity: minimal


test_script:
  - REM cd C:\projects\cefsharp\CefSharp.Test\bin\x86\%configuration%\
  - cd
  - REM copy C:\Tools\xUnit\*.*
  - REM xunit.console.clr4.x86 CefSharp.Test.dll /appveyor

after_test:
  - cmd: cd \projects\cefsharp\NuGet
  - cmd: pack.bat

artifacts:
  - path: NuGet\*.nupkg

matrix:
  allow_failures:
    - platform: Win32
      configuration: Release
    - platform: x86
      configuration: Release
