image: Visual Studio 2015

version: 65.0.0-CI{build}

clone_depth: 10

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1

# Disable tests
test: off

artifacts:
  - path: NuGet\*.nupkg
    name: nupkgfiles

# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/api/v2/package
  api_key:
    secure: 4b+nkwYBMwlOtLjGCHbbRXvtIhRQAQekYq/PBIox0Yn2PnSrIpMgzsu5YDgId+1I
  skip_symbols: false
  symbol_server: https://www.myget.org/F/cefsharp/api/v2/package
  artifact: nupkgfiles
