image: Visual Studio 2015

version: 73.1.130-CI{build}

clone_depth: 10

#Skip builing if we only modify text files
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - '**/*.js'

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1

# Disable tests
test: off

artifacts:
  - path: NuGet\*.nupkg
    name: nupkgfiles

# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/api/v2/package
  api_key:
    secure: q//EEhpYkeC7JaxBiK6ebPFiF3ixBi62pNWk0p7UIh8o/7Tm25DvbZPOoKf9dwsY
  skip_symbols: false
  symbol_server: https://www.myget.org/F/cefsharp/api/v2/package
  artifact: nupkgfiles
