version: 87.1.131-RCI{build}

image:
  - Visual Studio 2015
  - Visual Studio 2019

clone_depth: 10

matrix:
  fast_finish: true
  
configuration: Release

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
    build_script:
        - ps: .\build.ps1
    test:
        # Test our Release x64 build
        assemblies:
            - CefSharp.Test\bin\x64\Release\CefSharp.Test.dll
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
        - ps: .\build.netcore.ps1
    test_script:
        # Test our Release x64 build
        dotnet test CefSharp.Test\bin.netcore\x64\Release\netcoreapp3.1\CefSharp.Test.dll

artifacts:
  - path: NuGet\**\*.nupkg
    name: nupkgfiles

# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/api/v2/package
  api_key:
    secure: V8du2PPvMPok3Ya701jt5v2XWQgOZf52/H5wDHXBpKvXYkIIe8sonhVUy2TmEkqt
  skip_symbols: true
  symbol_server: https://www.myget.org/F/cefsharp/api/v2/package
  artifact: nupkgfiles

#Skip builing if we only modify text files
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.txt'
