environment:
  VisualStudioVersion: 11.0

version: 37.0.0-CI{build}
  
shallow_clone: true

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1
  
# Disable tests
test: off

artifacts:
  - path: NuGet\*.nupkg
    name: nupkgfiles

# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/
  api_key:
    secure: T3yoLSioRwXa7byUvu17t4I88RTQTvICh2j+KplLb1YVimd1IYy2m2akGqgOMJhY
  skip_symbols: true
  artifact: nupkgfiles